from __future__ import annotations

from graph.state import IoC
from agents.schemas import BilboSTIXSchema, BilboSigmaRuleSchema
from tools.safe_util import escape_yara_string, escape_sigma_value


def export_stix2(iocs: list[IoC]) -> dict:
    return BilboSTIXSchema(
        objects=[
            {
                "type": "indicator",
                "value": ioc.get("value"),
                "pattern": f"[{escape_sigma_value(ioc.get('type', ''))}:value = '{escape_sigma_value(ioc.get('value', ''))}']",
            }
            for ioc in iocs
        ],
    ).model_dump()


def export_yara(iocs: list[IoC]) -> str:
    rules = ["rule mordor_auto_ioc {"]
    rules.append("    meta:")
    rules.append('        description = "Auto-generated by MORDOR"')
    rules.append("    strings:")
    for i, ioc in enumerate(iocs):
        val = escape_yara_string(ioc.get("value", ""))
        rules.append(f'        $ioc_{i} = "{val}"')
    rules.append("    condition:")
    if len(iocs) >= 3:
        rules.append(f"        {len(iocs)} of ($ioc_*)")
    elif len(iocs) >= 1:
        rules.append("        any of them")
    else:
        rules.append("        false")
    rules.append("}")
    return "\n".join(rules)


def export_sigma(iocs: list[IoC]) -> dict:
    return BilboSigmaRuleSchema(
        detection={
            "selection": {
                f"ioc_{i}": escape_sigma_value(ioc.get("value")) for i, ioc in enumerate(iocs)
            },
            "condition": "selection",
        },
    ).model_dump()
